name: .NET CI

on:
  push:
    branches: [ "test-CICD" ]
  pull_request:
    branches: [ "test-CICD" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run All Tests
      id: demo
      run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --logger:"trx"

    - name: Run E2E Tests
      run: dotnet test MainApp.E2ETests/MainApp.E2ETests.csproj --no-build --configuration Release --logger:"trx"

    - name: The demo step has failed

      if: ${{ failure() && steps.demo.conclusion == 'failure' || jobs.steps.demo.conclusion == 'failure'}}
      run: echo "The demo step has failed. Please check the logs for details."

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/*.trx'

